export const oneCase = [
  {
    ins_grp_id: 2,
    phone2: '',
    estimate_file_id: '',
    ro_id: '',
    support_number: '',
    first_name: '',
    owner_user_id: 68,
    phone1: '',
    envelope_id: 17047,
    last_name: '',
    vehicle: {
      vehicle_milage: 0,
      vehicle_stage: 0,
      impact1: null,
      vehicle_color: '',
      vehicle_production: '',
      vehicle_mvdg_code: '',
      paint_cd3: '',
      vehicle_makecode: 0,
      db_v_code: '',
      plate_state: null,
      plate_number: '',
      vehicle_tone: 0,
      vehicle_production_year: 9999,
      vehicle_type: '',
      vehicle_memo: '',
      paint_cd1: '',
      vehicle_condition: '',
      vehicle_style: '',
      vehicle_engine: '',
      vehicle_model: '',
      vehicle_make_desc: '(No Make)',
      vehicle_trim_color: '',
      impact2: null,
      vehicle_trim_code: '',
      vehicle_vin: '(No VIN)',
      dmg_memo: '',
      paint_cd2: '',
    },
    estimate_country: '',
    manually_added: 1,
    arrival_type: 0,
    is_review: '1',
    ems_version: '',
    vehicle_action: 0,
    status: 0,
    details: [],
    addr1: '',
    state: '',
    database_date: '2020-10-27 03:57:20',
    envelope_name: '(No VIN)',
    zip: '',
    unique_id: '',
    claim_number: '',
    email: '',
    create_date: '2020-03-20 07:07:46',
    transmit_date: '2020-10-27 03:57:20',
    city: '',
    software_version: '',
    country: null,
    mcf: 0,
    est_system: '',
    notif_type: '0',
    company_id: 1851,
  },
  {
    is_review: '1',
    status: 0,
    vehicle_action: 0,
    ems_version: '',
    arrival_type: 0,
    database_date: '2020-10-26 03:58:07',
    envelope_name: 'XCXCASCASC',
    state: null,
    addr1: null,
    first_name: null,
    phone2: null,
    ins_grp_id: 0,
    estimate_file_id: '',
    ro_id: '',
    support_number: '',
    vehicle: {
      vehicle_mvdg_code: '',
      paint_cd3: '',
      vehicle_makecode: 0,
      plate_state: null,
      plate_number: '446655',
      db_v_code: '',
      vehicle_tone: 0,
      vehicle_milage: 0,
      vehicle_stage: 0,
      vehicle_color: '',
      impact1: null,
      vehicle_production: '',
      vehicle_trim_color: '',
      impact2: null,
      vehicle_trim_code: '',
      vehicle_vin: 'XCXCASCASC',
      dmg_memo: '',
      paint_cd2: '',
      vehicle_production_year: 2019,
      vehicle_type: '',
      vehicle_memo: '',
      paint_cd1: '',
      vehicle_condition: '',
      vehicle_engine: '',
      vehicle_model: 'Mustang',
      vehicle_style: '',
      vehicle_make_desc: 'Ford',
    },
    estimate_country: '',
    manually_added: 1,
    phone1: null,
    last_name: null,
    envelope_id: 18747,
    owner_user_id: 68,
    city: null,
    transmit_date: '2020-10-26 03:58:07',
    email: null,
    create_date: '2020-06-26 13:11:53',
    company_id: 1851,
    mcf: 0,
    est_system: '',
    notif_type: '0',
    country: null,
    software_version: '',
    zip: null,
    claim_number: '',
    unique_id: '',
  },
]
