export const LOGIN = 'LOGIN'
export const LOGIN_ASYNC = 'LOGIN_ASYNC'
export const PING = 'PING'
export const PING_ASYNC = 'PING_ASYNC'
export const CASES = 'CASES'
export const CASES_ASYNC = 'CASES_ASYNC'
export const SET_COMPANY_ID = 'SET_COMPANY_ID'
export const LOGOUT = 'LOGOUT'